In [ ]:
#First, we always need this line to use NumPy
import numpy as np
#This just means "bring in NumPy and let me call it np for short."

In [ ]:
#1. Make an array from a list
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [ ]:
#2. Make an array of all zeros
zeros = np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


In [ ]:
#3. Make an array of all ones
ones = np.ones(4)
print(ones)

[1. 1. 1. 1.]


In [ ]:
#4. Make an array with a range of numbers
r = np.arange(1,6)
print(r)

[1 2 3 4 5]


In [ ]:
#5. Make evenly spaced numbers
lin = np.linspace(0, 10, 5)
print(lin)

[ 0.   2.5  5.   7.5 10. ]


In [3]:
import numpy as np
arr=np.array([[1,2,3],
             [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#1. .shape — how many rows and columns?
print(arr.shape)

(2, 3)


In [5]:
#2. .ndim — how many dimensions?
print(arr.ndim)

2


In [6]:
#3. .size — how many total numbers are in it?
print(arr.dtype)

int32
