In [ ]:
#1. Indexing a 1D array (simple list-like array)

import numpy as np
arr = np.array([10,20,30,40,50])

print(arr[0])
print(arr[1])
print(arr[-1])


10
20
50


In [ ]:
#2. Slicing a 1D array

print(arr[1:4])
print(arr[:3])
print(arr[2:])

[20 30 40]
[10 20 30]
[30 40 50]


In [7]:
#3. Indexing a 2D array (rows and columns)

grid = np.array([[1,2,3],
                 [4,5,6]])
print(grid[0,1])
print(grid[1,2])

2
6


In [ ]:
#4. Slicing a 2D array

print(grid[0,:])
print(grid[:,1])

[1 2 3]
[2 5]
