In [1]:
#1. Math directly on an array

import numpy as np
arr = np.array([10,20,30,40])

print(arr + 5)
print(arr - 5)
print(arr * 5)
print(arr / 5)


[15 25 35 45]
[ 5 15 25 35]
[ 50 100 150 200]
[2. 4. 6. 8.]


In [5]:
#2. Math between two arrays (same size)

a = np.array([1,2,3,])
b = np.array([10,20,30])

print(a * b)
print(a + b)
print(a - b)
print(a / b)

[10 40 90]
[11 22 33]
[ -9 -18 -27]
[0.1 0.1 0.1]


In [6]:
#3. Useful math functions

nums = np.array([10,20,30,40,50])

print(np.sum(nums))
print(np.mean(nums))
print(np.min(nums))
print(np.max(nums))

150
30.0
10
50
