In [ ]:
#1. .reshape() — change rows and columns

import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr.shape)

reshaped = arr.reshape(2,3)
print(reshaped)

reshaped2 = arr.reshape(3,2)
print(reshaped2)

(6,)
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [9]:
#2. .flatten() — turn it back into one line

import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

reshaped = arr.flatten()
print(reshaped)


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
