In [ ]:
#1. Simple example — array + single number 
# (you already know this one)

import numpy as np
arr=np.array([1,2,3])
print(arr+10)

#The 10 is "broadcast" across all 3 items.

[11 12 13]


In [ ]:
#2. Bigger example — 2D array + 1D array

grid = np.array([[1,2,3],
                 [4,5,6]])
row = np.array([10,20,30])

print(grid + row)

#The row array has 3 numbers, matching the 3 columns of grid.
#  NumPy automatically repeats row for each row of grid and adds them.

[[11 22 33]
 [14 25 36]]


In [ ]:
# 3. The one rule to remember

# Broadcasting only works if the shapes are compatible. 
# Simple version of the rule:

# Either the sizes match, OR
# One of them is size 1 (so it can be "stretched")

# If neither is true, you'll get an error like ValueError: 
# shapes not aligned.