In [ ]:
#1. The basic idea

import numpy as np
arr = np.array([2,4,6,7,9,6,8,3,1])

condition = arr > 5
print(condition)

# NumPy checks every item against the condition and gives back True/False for each one.
#  This True/False array is called a mask.

[False False  True  True  True  True  True False False]
[6 7 9 6 8]


In [ ]:
#2. Using the mask to actually get the values

result = arr[arr > 5]
print(result)

#This says: "Only keep the items where the condition was True.
# " Super useful — this is like filtering in Excel or SQL, but for arrays.

In [ ]:
#3. Combining conditions

result = arr[(arr > 3) & (arr < 9)]
print (result)

#Always wrap each condition in () when combining them
#  — this is a common beginner mistake if skipped.

[4 6 7 6 8]


In [7]:
#4. Changing values using a mask

arr [arr > 5] = 0
print (arr)

[2 4 0 0 0 0 0 3 1]
