In [ ]:
#1. Basic example

import numpy as np
arr = np.array([10,20,30,40,50])
result = arr[[0, 2, 4]]
print(result)

# Instead of arr[0], arr[2], arr[4] one at a time, 
# we give a list of positions [0, 2, 4] and get all of them back at once.

[10 30 50]


In [ ]:
#2. You can also repeat or reorder indexes
result = arr[[2,2,2]]
print(result)

#we can even grab the same index twice,
#  or pick items in a different order than they appear.

[30 30 30]


In [ ]:
#3. Fancy indexing on a 2D array

grid = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

result = grid[[0,2]]
print(result)

#This picks out row 0 and row 2 completely.

[[1 2 3]
 [7 8 9]]


In [13]:
#4. Picking specific (row, column) pairs

rusult = grid[[0,1,2],[0,1,2]]
print (result)

# This pairs them up: (row 0, col 0) → 1, (row 1, col 1) → 
# 5, (row 2, col 2) → 9. This grabs the diagonal!

[[1 2 3]
 [7 8 9]]
