In [ ]:
#1. The problem: sum of the whole grid

import numpy as np
grid = np.array([[1,2,3],
                 [4,5,6]])
print(np.sum(grid))

21


In [ ]:
#2. axis=0 — sum DOWN each column

print(np.sum(grid,axis=0))


#Column 1: 1+4=5, Column 2: 2+5=7, Column 3: 3+6=9.

[5 7 9]


In [ ]:
#3. axis=1 — sum ACROSS each row

print(np.sum(grid,axis=1))


#Row 1: 1+2+3=6, Row 2: 4+5+6=15.

[ 6 15]


In [ ]:
#4. Works with other functions too
print (np.mean(grid,axis=0))
print(np.max(grid,axis=1))


[2.5 3.5 4.5]
[3 6]


In [16]:
import numpy as np
sales = np.array([[100,200,300,400],
                 [10,20,30,40],
                 [1,2,3,4]])
np.sum(sales,axis=1)
np.sum(sales,axis=0)

array([111, 222, 333, 444])

In [22]:
import numpy as np

sales = np.array([
    #Jen  #Feb #Mar #Apr
    [100, 200, 150, 300],  # Product A
    [200, 150, 250, 100],  # Product B
    [300, 100, 200, 250]   # Product C
])
month_sales=np.sum(sales, axis=1)
prodect_sales=np.sum(sales, axis=0)

print("Total month sales:",month_sales)
print('total prodect sales:',prodect_sales)

Total month sales: [750 700 850]
total prodect sales: [600 450 600 650]
