In [ ]:
#1. np.concatenate() — join arrays end to end

import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
result = np.concatenate((a,b))
print (result)

#Just glues them together, one after the other.

[1 2 3 4 5 6]


In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
vertical_stack=result = np.vstack((b,a))
#"v" = vertical. Think of it like stacking two rows on top of each other to make a grid.
horizondel_stack=result = np.hstack((b,a))
#"h" = horizontal. For 1D arrays this looks the same as concatenate, but it becomes clearer with 2D arrays:
print(horizondel_stack)
print(vertical_stack)



[4 5 6 1 2 3]
[[4 5 6]
 [1 2 3]]


In [9]:
import numpy as np 
a= np.array([[1],[2]])
b = np.array([[3],[4]])
result=np.hstack((a,b))
print(result)

[[1 3]
 [2 4]]


In [10]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
result = np.split(arr,3)
print(result)


[array([1, 2]), array([3, 4]), array([5, 6])]
