In [ ]:
#1. Random decimal numbers between 0 and 1

import numpy as np
r = np.random.rand(3)
print(r)
# rand(3) gives you 3 random decimal numbers, each between 0 and 1. The exact numbers will be different every time you run it.

[0.47093961 0.75001922 0.66355281]


In [ ]:
#2. Random whole numbers (integers) in a range

num = np.random.randint(0,10,size=5)
print(num)

# This means: "give me 5 random whole numbers between 1 and 9" (10 is not included, just like slicing).

[4 7 7 1 4]


In [ ]:
# 3. Random numbers arranged in a grid
r = np.random.rand(2,3)
print(r)

# Same idea, but shaped into 2 rows and 3 columns.


[[0.28210933 0.5788347  0.94166581]
 [0.67828198 0.08120358 0.75238312]]


In [ ]:
# 4. np.random.seed() — make randomness repeatable

r = np.random.seed(40)
print(np.random.randint(0,10,size=3))

# Normally random numbers are different every time. But if you set a seed,
#  you'll get the same "random" numbers every time — very useful so your code gives consistent,
#  testable results.

[6 7 5]
