In [5]:
# 1. np.sort() — arrange values from smallest to biggest

import numpy as np
arr = np.array([2,3,7,4,8,5,1,9])
result = np.sort(arr)
print (result)

# Simple — just puts everything in order, smallest first.

[1 2 3 4 5 7 8 9]


In [ ]:
# 2. np.argsort() — get the positions that would sort it

result = np.argsort(arr)
print(result)

# This is a bit tricky at first. It's saying: "If you want the array sorted, take the item at index 1 first, then index 3, then index 0..."


[6 0 1 3 5 2 4 7]


In [10]:
# 3. np.where() — find positions matching a condition

arr = np.array([10,20,30,45])
result = np.where(arr<20)
print(result)
print(arr[np.where(arr<20)])
print('tha valus of this array',arr[result])

# This tells you the index positions where the condition is True — here, positions 1, 2, and 4 have values greater than 20.

(array([0], dtype=int64),)
[10]
tha valus of this array [10]
